[debug]
enable_profiler = true

[render]
render_radius_xz = 4
render_radius_y = 1

[player]
spawn_x = 0.0
spawn_y = 10.0
spawn_z = 0.0
mouse_sensitivity = 0.0022
eye_height = 1.62
radius = 0.3
height = 1.8
double_tap_window = 0.25
collision_steps = 3
walk_speed = 5.0
walk_sprint_multiplier = 1.8
walk_accel = 45.0
air_accel = 10.0
ground_friction = 14.0
air_friction = 1.0
jump_speed = 8.5
gravity = 24.0
fly_speed = 7.0
fly_sprint_multiplier = 2.5
fly_accel = 24.0
fly_friction = 10.0

[world]
seed = 12345
